server:
  port: 8080

logging:
  level:
    com.example: INFO
    org.springframework.web: INFO
  file: logs/myapp.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
